# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b14428a1277d8145517aa5b04011149b8880a69a26f050849981ef69c01a3ddfe3adf06674e89289d97907a4236eebc7dafe89f31b131a925d8de51e03ba7908

test:
  secret_key_base: 29533a16ee7d92c2134fba8ee0d525abefbaa86388182228a5cb5bdcbacfef5bb2609d08ffc4fb189179e50a0e9839a86724aa2d27050cc32de2ee72ec086d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
